apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: store-front-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store-front
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
